// GENERATED by scripts/generate-categories.mjs from docs/taxonomy.md.
// Edit the markdown and re-run `node scripts/generate-categories.mjs`.
import type { Category } from "@/types";
import type { SelectOption } from "@/components/ui/select";

export const CATEGORIES: Category[] = [
  {
    "slug": "vehicles",
    "nameEn": "Vehicles",
    "nameUr": "گاڑیاں",
    "icon": "directions_car",
    "sort": 1,
    "subcategories": [
      {
        "slug": "vehicles-cars",
        "nameEn": "Cars",
        "nameUr": "Cars"
      },
      {
        "slug": "vehicles-suvs-jeeps",
        "nameEn": "SUVs & Jeeps",
        "nameUr": "SUVs & Jeeps"
      },
      {
        "slug": "vehicles-vans-hiace",
        "nameEn": "Vans & Hiace",
        "nameUr": "Vans & Hiace"
      },
      {
        "slug": "vehicles-pickups-loaders",
        "nameEn": "Pickups & Loaders",
        "nameUr": "Pickups & Loaders"
      },
      {
        "slug": "vehicles-trucks-mazda",
        "nameEn": "Trucks & Mazda",
        "nameUr": "Trucks & Mazda"
      },
      {
        "slug": "vehicles-buses-coaches",
        "nameEn": "Buses & Coaches",
        "nameUr": "Buses & Coaches"
      },
      {
        "slug": "vehicles-rickshaws-chingchi",
        "nameEn": "Rickshaws & Chingchi",
        "nameUr": "Rickshaws & Chingchi"
      },
      {
        "slug": "vehicles-tractors",
        "nameEn": "Tractors",
        "nameUr": "Tractors"
      },
      {
        "slug": "vehicles-motorcycles",
        "nameEn": "Motorcycles",
        "nameUr": "Motorcycles"
      },
      {
        "slug": "vehicles-scooties",
        "nameEn": "Scooties",
        "nameUr": "Scooties"
      },
      {
        "slug": "vehicles-heavy-machinery-vehicles",
        "nameEn": "Heavy Machinery Vehicles",
        "nameUr": "Heavy Machinery Vehicles"
      },
      {
        "slug": "vehicles-ncp-non-custom-paid-vehicles",
        "nameEn": "NCP / Non-Custom Paid Vehicles",
        "nameUr": "NCP / Non-Custom Paid Vehicles"
      },
      {
        "slug": "vehicles-vehicle-rental-hire",
        "nameEn": "Vehicle Rental & Hire",
        "nameUr": "Vehicle Rental & Hire"
      },
      {
        "slug": "vehicles-auto-parts-spares",
        "nameEn": "Auto Parts & Spares",
        "nameUr": "Auto Parts & Spares"
      },
      {
        "slug": "vehicles-tyres-rims",
        "nameEn": "Tyres & Rims",
        "nameUr": "Tyres & Rims"
      },
      {
        "slug": "vehicles-vehicle-batteries",
        "nameEn": "Vehicle Batteries",
        "nameUr": "Vehicle Batteries"
      },
      {
        "slug": "vehicles-car-audio-video",
        "nameEn": "Car Audio & Video",
        "nameUr": "Car Audio & Video"
      },
      {
        "slug": "vehicles-car-care-accessories",
        "nameEn": "Car Care & Accessories",
        "nameUr": "Car Care & Accessories"
      },
      {
        "slug": "vehicles-bicycles",
        "nameEn": "Bicycles",
        "nameUr": "Bicycles"
      },
      {
        "slug": "vehicles-atv-quad-bikes",
        "nameEn": "ATV & Quad Bikes",
        "nameUr": "ATV & Quad Bikes"
      },
      {
        "slug": "vehicles-boats-water-transport",
        "nameEn": "Boats & Water Transport",
        "nameUr": "Boats & Water Transport"
      },
      {
        "slug": "vehicles-other",
        "nameEn": "Other Vehicles",
        "nameUr": "Other Vehicles"
      }
    ]
  },
  {
    "slug": "property-for-sale",
    "nameEn": "Property for Sale",
    "nameUr": "جائیداد برائے فروخت",
    "icon": "home_work",
    "sort": 2,
    "subcategories": [
      {
        "slug": "property-for-sale-residential-plot",
        "nameEn": "Residential Plot",
        "nameUr": "Residential Plot"
      },
      {
        "slug": "property-for-sale-commercial-plot",
        "nameEn": "Commercial Plot",
        "nameUr": "Commercial Plot"
      },
      {
        "slug": "property-for-sale-agricultural-land",
        "nameEn": "Agricultural Land",
        "nameUr": "Agricultural Land"
      },
      {
        "slug": "property-for-sale-orchard",
        "nameEn": "Orchard (Bagh)",
        "nameUr": "Orchard (Bagh)"
      },
      {
        "slug": "property-for-sale-house",
        "nameEn": "House",
        "nameUr": "House"
      },
      {
        "slug": "property-for-sale-flat-apartment",
        "nameEn": "Flat & Apartment",
        "nameUr": "Flat & Apartment"
      },
      {
        "slug": "property-for-sale-portion-floor",
        "nameEn": "Portion / Floor",
        "nameUr": "Portion / Floor"
      },
      {
        "slug": "property-for-sale-shop",
        "nameEn": "Shop",
        "nameUr": "Shop"
      },
      {
        "slug": "property-for-sale-office",
        "nameEn": "Office",
        "nameUr": "Office"
      },
      {
        "slug": "property-for-sale-plaza-building",
        "nameEn": "Plaza & Building",
        "nameUr": "Plaza & Building"
      },
      {
        "slug": "property-for-sale-warehouse-godown",
        "nameEn": "Warehouse & Godown",
        "nameUr": "Warehouse & Godown"
      },
      {
        "slug": "property-for-sale-farmhouse",
        "nameEn": "Farmhouse",
        "nameUr": "Farmhouse"
      },
      {
        "slug": "property-for-sale-marriage-hall",
        "nameEn": "Marriage Hall",
        "nameUr": "Marriage Hall"
      },
      {
        "slug": "property-for-sale-petrol-pump",
        "nameEn": "Petrol Pump",
        "nameUr": "Petrol Pump"
      },
      {
        "slug": "property-for-sale-factory-industrial-unit",
        "nameEn": "Factory & Industrial Unit",
        "nameUr": "Factory & Industrial Unit"
      },
      {
        "slug": "property-for-sale-hujra-guest-house",
        "nameEn": "Hujra & Guest House",
        "nameUr": "Hujra & Guest House"
      },
      {
        "slug": "property-for-sale-other",
        "nameEn": "Other Property",
        "nameUr": "Other Property"
      }
    ]
  },
  {
    "slug": "property-for-rent",
    "nameEn": "Property for Rent",
    "nameUr": "جائیداد برائے کرایہ",
    "icon": "vpn_key",
    "sort": 3,
    "subcategories": [
      {
        "slug": "property-for-rent-house-for-rent",
        "nameEn": "House for Rent",
        "nameUr": "House for Rent"
      },
      {
        "slug": "property-for-rent-flat-apartment",
        "nameEn": "Flat & Apartment",
        "nameUr": "Flat & Apartment"
      },
      {
        "slug": "property-for-rent-room-portion",
        "nameEn": "Room / Portion",
        "nameUr": "Room / Portion"
      },
      {
        "slug": "property-for-rent-shop-for-rent",
        "nameEn": "Shop for Rent",
        "nameUr": "Shop for Rent"
      },
      {
        "slug": "property-for-rent-office-for-rent",
        "nameEn": "Office for Rent",
        "nameUr": "Office for Rent"
      },
      {
        "slug": "property-for-rent-warehouse-godown",
        "nameEn": "Warehouse & Godown",
        "nameUr": "Warehouse & Godown"
      },
      {
        "slug": "property-for-rent-hall-marquee",
        "nameEn": "Hall & Marquee",
        "nameUr": "Hall & Marquee"
      },
      {
        "slug": "property-for-rent-agricultural-land-lease",
        "nameEn": "Agricultural Land Lease",
        "nameUr": "Agricultural Land Lease"
      },
      {
        "slug": "property-for-rent-orchard-lease",
        "nameEn": "Orchard Lease (Theka)",
        "nameUr": "Orchard Lease (Theka)"
      },
      {
        "slug": "property-for-rent-machinery-yard",
        "nameEn": "Machinery Yard",
        "nameUr": "Machinery Yard"
      },
      {
        "slug": "property-for-rent-guest-house-rooms",
        "nameEn": "Guest House & Rooms",
        "nameUr": "Guest House & Rooms"
      },
      {
        "slug": "property-for-rent-other",
        "nameEn": "Other Rentals",
        "nameUr": "Other Rentals"
      }
    ]
  },
  {
    "slug": "mobiles-tablets",
    "nameEn": "Mobiles & Tablets",
    "nameUr": "موبائل اور ٹیبلٹ",
    "icon": "smartphone",
    "sort": 4,
    "subcategories": [
      {
        "slug": "mobiles-tablets-mobile-phones",
        "nameEn": "Mobile Phones",
        "nameUr": "Mobile Phones"
      },
      {
        "slug": "mobiles-tablets-tablets",
        "nameEn": "Tablets",
        "nameUr": "Tablets"
      },
      {
        "slug": "mobiles-tablets-smart-watches",
        "nameEn": "Smart Watches",
        "nameUr": "Smart Watches"
      },
      {
        "slug": "mobiles-tablets-mobile-accessories",
        "nameEn": "Mobile Accessories",
        "nameUr": "Mobile Accessories"
      },
      {
        "slug": "mobiles-tablets-chargers-cables",
        "nameEn": "Chargers & Cables",
        "nameUr": "Chargers & Cables"
      },
      {
        "slug": "mobiles-tablets-covers-protectors",
        "nameEn": "Covers & Protectors",
        "nameUr": "Covers & Protectors"
      },
      {
        "slug": "mobiles-tablets-power-banks",
        "nameEn": "Power Banks",
        "nameUr": "Power Banks"
      },
      {
        "slug": "mobiles-tablets-earphones-headsets",
        "nameEn": "Earphones & Headsets",
        "nameUr": "Earphones & Headsets"
      },
      {
        "slug": "mobiles-tablets-sim-golden-numbers",
        "nameEn": "SIM & Golden Numbers",
        "nameUr": "SIM & Golden Numbers"
      },
      {
        "slug": "mobiles-tablets-mobile-spare-parts",
        "nameEn": "Mobile Spare Parts",
        "nameUr": "Mobile Spare Parts"
      },
      {
        "slug": "mobiles-tablets-mobile-repair-tools",
        "nameEn": "Mobile Repair Tools",
        "nameUr": "Mobile Repair Tools"
      },
      {
        "slug": "mobiles-tablets-other",
        "nameEn": "Other Mobile Items",
        "nameUr": "Other Mobile Items"
      }
    ]
  },
  {
    "slug": "electronics-home-appliances",
    "nameEn": "Electronics & Home Appliances",
    "nameUr": "الیکٹرونکس اور گھریلو سامان",
    "icon": "tv",
    "sort": 5,
    "subcategories": [
      {
        "slug": "electronics-home-appliances-led-smart-tvs",
        "nameEn": "LED & Smart TVs",
        "nameUr": "LED & Smart TVs"
      },
      {
        "slug": "electronics-home-appliances-refrigerators",
        "nameEn": "Refrigerators",
        "nameUr": "Refrigerators"
      },
      {
        "slug": "electronics-home-appliances-deep-freezers",
        "nameEn": "Deep Freezers",
        "nameUr": "Deep Freezers"
      },
      {
        "slug": "electronics-home-appliances-washing-machines-dryers",
        "nameEn": "Washing Machines & Dryers",
        "nameUr": "Washing Machines & Dryers"
      },
      {
        "slug": "electronics-home-appliances-air-conditioners",
        "nameEn": "Air Conditioners",
        "nameUr": "Air Conditioners"
      },
      {
        "slug": "electronics-home-appliances-air-coolers-room-coolers",
        "nameEn": "Air Coolers & Room Coolers",
        "nameUr": "Air Coolers & Room Coolers"
      },
      {
        "slug": "electronics-home-appliances-fans",
        "nameEn": "Fans (Ceiling, Pedestal, Exhaust)",
        "nameUr": "Fans (Ceiling, Pedestal, Exhaust)"
      },
      {
        "slug": "electronics-home-appliances-gas-electric-heaters",
        "nameEn": "Gas & Electric Heaters",
        "nameUr": "Gas & Electric Heaters"
      },
      {
        "slug": "electronics-home-appliances-water-dispensers",
        "nameEn": "Water Dispensers",
        "nameUr": "Water Dispensers"
      },
      {
        "slug": "electronics-home-appliances-geysers",
        "nameEn": "Geysers",
        "nameUr": "Geysers"
      },
      {
        "slug": "electronics-home-appliances-microwave-ovens",
        "nameEn": "Microwave & Ovens",
        "nameUr": "Microwave & Ovens"
      },
      {
        "slug": "electronics-home-appliances-blenders-juicers-grinders",
        "nameEn": "Blenders, Juicers & Grinders",
        "nameUr": "Blenders, Juicers & Grinders"
      },
      {
        "slug": "electronics-home-appliances-electric-kettles-toasters",
        "nameEn": "Electric Kettles & Toasters",
        "nameUr": "Electric Kettles & Toasters"
      },
      {
        "slug": "electronics-home-appliances-irons-steamers",
        "nameEn": "Irons & Steamers",
        "nameUr": "Irons & Steamers"
      },
      {
        "slug": "electronics-home-appliances-vacuum-cleaners",
        "nameEn": "Vacuum Cleaners",
        "nameUr": "Vacuum Cleaners"
      },
      {
        "slug": "electronics-home-appliances-sewing-machines",
        "nameEn": "Sewing Machines",
        "nameUr": "Sewing Machines"
      },
      {
        "slug": "electronics-home-appliances-water-pumps-motors",
        "nameEn": "Water Pumps & Motors",
        "nameUr": "Water Pumps & Motors"
      },
      {
        "slug": "electronics-home-appliances-audio-speakers-home-theatre",
        "nameEn": "Audio, Speakers & Home Theatre",
        "nameUr": "Audio, Speakers & Home Theatre"
      },
      {
        "slug": "electronics-home-appliances-dish-satellite-receivers",
        "nameEn": "Dish, Satellite & Receivers",
        "nameUr": "Dish, Satellite & Receivers"
      },
      {
        "slug": "electronics-home-appliances-cctv-security-systems",
        "nameEn": "CCTV & Security Systems",
        "nameUr": "CCTV & Security Systems"
      },
      {
        "slug": "electronics-home-appliances-voltage-stabilizers",
        "nameEn": "Voltage Stabilizers",
        "nameUr": "Voltage Stabilizers"
      },
      {
        "slug": "electronics-home-appliances-kitchen-appliances",
        "nameEn": "Kitchen Appliances",
        "nameUr": "Kitchen Appliances"
      },
      {
        "slug": "electronics-home-appliances-other",
        "nameEn": "Other Appliances",
        "nameUr": "Other Appliances"
      }
    ]
  },
  {
    "slug": "computers-it",
    "nameEn": "Computers & IT",
    "nameUr": "کمپیوٹر اور آئی ٹی",
    "icon": "computer",
    "sort": 6,
    "subcategories": [
      {
        "slug": "computers-it-laptops",
        "nameEn": "Laptops",
        "nameUr": "Laptops"
      },
      {
        "slug": "computers-it-desktop-computers",
        "nameEn": "Desktop Computers",
        "nameUr": "Desktop Computers"
      },
      {
        "slug": "computers-it-monitors-displays",
        "nameEn": "Monitors & Displays",
        "nameUr": "Monitors & Displays"
      },
      {
        "slug": "computers-it-printers-scanners",
        "nameEn": "Printers & Scanners",
        "nameUr": "Printers & Scanners"
      },
      {
        "slug": "computers-it-computer-components",
        "nameEn": "Computer Components (RAM, SSD, GPU)",
        "nameUr": "Computer Components (RAM, SSD, GPU)"
      },
      {
        "slug": "computers-it-networking",
        "nameEn": "Networking (Routers, ONU, Switches)",
        "nameUr": "Networking (Routers, ONU, Switches)"
      },
      {
        "slug": "computers-it-computer-accessories",
        "nameEn": "Computer Accessories",
        "nameUr": "Computer Accessories"
      },
      {
        "slug": "computers-it-software-licences",
        "nameEn": "Software & Licences",
        "nameUr": "Software & Licences"
      },
      {
        "slug": "computers-it-gaming-consoles-games",
        "nameEn": "Gaming Consoles & Games",
        "nameUr": "Gaming Consoles & Games"
      },
      {
        "slug": "computers-it-pos-billing-systems",
        "nameEn": "POS & Billing Systems",
        "nameUr": "POS & Billing Systems"
      },
      {
        "slug": "computers-it-ups-for-computers",
        "nameEn": "UPS for Computers",
        "nameUr": "UPS for Computers"
      },
      {
        "slug": "computers-it-other",
        "nameEn": "Other IT Equipment",
        "nameUr": "Other IT Equipment"
      }
    ]
  },
  {
    "slug": "solar-energy",
    "nameEn": "Solar & Energy",
    "nameUr": "سولر اور توانائی",
    "icon": "solar_power",
    "sort": 7,
    "subcategories": [
      {
        "slug": "solar-energy-solar-panels",
        "nameEn": "Solar Panels",
        "nameUr": "Solar Panels"
      },
      {
        "slug": "solar-energy-solar-inverters",
        "nameEn": "Solar Inverters",
        "nameUr": "Solar Inverters"
      },
      {
        "slug": "solar-energy-solar-batteries",
        "nameEn": "Solar Batteries",
        "nameUr": "Solar Batteries"
      },
      {
        "slug": "solar-energy-complete-solar-systems",
        "nameEn": "Complete Solar Systems",
        "nameUr": "Complete Solar Systems"
      },
      {
        "slug": "solar-energy-solar-structures-mounting",
        "nameEn": "Solar Structures & Mounting",
        "nameUr": "Solar Structures & Mounting"
      },
      {
        "slug": "solar-energy-solar-water-pumps",
        "nameEn": "Solar Water Pumps",
        "nameUr": "Solar Water Pumps"
      },
      {
        "slug": "solar-energy-solar-geysers",
        "nameEn": "Solar Geysers",
        "nameUr": "Solar Geysers"
      },
      {
        "slug": "solar-energy-solar-lights-fans",
        "nameEn": "Solar Lights & Fans",
        "nameUr": "Solar Lights & Fans"
      },
      {
        "slug": "solar-energy-wiring-breakers-db-boards",
        "nameEn": "Wiring, Breakers & DB Boards",
        "nameUr": "Wiring, Breakers & DB Boards"
      },
      {
        "slug": "solar-energy-generators",
        "nameEn": "Generators",
        "nameUr": "Generators"
      },
      {
        "slug": "solar-energy-ups-batteries",
        "nameEn": "UPS & Batteries",
        "nameUr": "UPS & Batteries"
      },
      {
        "slug": "solar-energy-biogas-units",
        "nameEn": "Biogas Units",
        "nameUr": "Biogas Units"
      },
      {
        "slug": "solar-energy-installation-services-kits",
        "nameEn": "Installation Services & Kits",
        "nameUr": "Installation Services & Kits"
      },
      {
        "slug": "solar-energy-other",
        "nameEn": "Other Energy Equipment",
        "nameUr": "Other Energy Equipment"
      }
    ]
  },
  {
    "slug": "agriculture-farming",
    "nameEn": "Agriculture & Farming",
    "nameUr": "زراعت",
    "icon": "agriculture",
    "sort": 8,
    "subcategories": [
      {
        "slug": "agriculture-farming-tractors-implements",
        "nameEn": "Tractors & Implements",
        "nameUr": "Tractors & Implements"
      },
      {
        "slug": "agriculture-farming-thresher-harvester",
        "nameEn": "Thresher & Harvester",
        "nameUr": "Thresher & Harvester"
      },
      {
        "slug": "agriculture-farming-ploughs-cultivators",
        "nameEn": "Ploughs & Cultivators",
        "nameUr": "Ploughs & Cultivators"
      },
      {
        "slug": "agriculture-farming-trolleys-trailers",
        "nameEn": "Trolleys & Trailers",
        "nameUr": "Trolleys & Trailers"
      },
      {
        "slug": "agriculture-farming-tube-wells-pumps",
        "nameEn": "Tube Wells & Pumps",
        "nameUr": "Tube Wells & Pumps"
      },
      {
        "slug": "agriculture-farming-sprayers-dusters",
        "nameEn": "Sprayers & Dusters",
        "nameUr": "Sprayers & Dusters"
      },
      {
        "slug": "agriculture-farming-chaff-cutters",
        "nameEn": "Chaff Cutters (Toka Machine)",
        "nameUr": "Chaff Cutters (Toka Machine)"
      },
      {
        "slug": "agriculture-farming-seeds-saplings",
        "nameEn": "Seeds & Saplings",
        "nameUr": "Seeds & Saplings"
      },
      {
        "slug": "agriculture-farming-fertilizers",
        "nameEn": "Fertilizers",
        "nameUr": "Fertilizers"
      },
      {
        "slug": "agriculture-farming-pesticides-herbicides",
        "nameEn": "Pesticides & Herbicides",
        "nameUr": "Pesticides & Herbicides"
      },
      {
        "slug": "agriculture-farming-irrigation-pipes-drip-systems",
        "nameEn": "Irrigation Pipes & Drip Systems",
        "nameUr": "Irrigation Pipes & Drip Systems"
      },
      {
        "slug": "agriculture-farming-tunnel-greenhouse-farming",
        "nameEn": "Tunnel & Greenhouse Farming",
        "nameUr": "Tunnel & Greenhouse Farming"
      },
      {
        "slug": "agriculture-farming-farm-hand-tools",
        "nameEn": "Farm Hand Tools",
        "nameUr": "Farm Hand Tools"
      },
      {
        "slug": "agriculture-farming-poultry-farm-equipment",
        "nameEn": "Poultry Farm Equipment",
        "nameUr": "Poultry Farm Equipment"
      },
      {
        "slug": "agriculture-farming-dairy-farm-equipment",
        "nameEn": "Dairy Farm Equipment",
        "nameUr": "Dairy Farm Equipment"
      },
      {
        "slug": "agriculture-farming-beekeeping-equipment",
        "nameEn": "Beekeeping Equipment",
        "nameUr": "Beekeeping Equipment"
      },
      {
        "slug": "agriculture-farming-grading-packing-crates",
        "nameEn": "Grading, Packing & Crates",
        "nameUr": "Grading, Packing & Crates"
      },
      {
        "slug": "agriculture-farming-cold-storage",
        "nameEn": "Cold Storage",
        "nameUr": "Cold Storage"
      },
      {
        "slug": "agriculture-farming-other",
        "nameEn": "Other Agricultural Items",
        "nameUr": "Other Agricultural Items"
      }
    ]
  },
  {
    "slug": "livestock-animals",
    "nameEn": "Livestock & Animals",
    "nameUr": "مویشی اور جانور",
    "icon": "pets",
    "sort": 9,
    "subcategories": [
      {
        "slug": "livestock-animals-cows",
        "nameEn": "Cows",
        "nameUr": "Cows"
      },
      {
        "slug": "livestock-animals-buffaloes",
        "nameEn": "Buffaloes",
        "nameUr": "Buffaloes"
      },
      {
        "slug": "livestock-animals-bulls-oxen",
        "nameEn": "Bulls & Oxen",
        "nameUr": "Bulls & Oxen"
      },
      {
        "slug": "livestock-animals-calves",
        "nameEn": "Calves",
        "nameUr": "Calves"
      },
      {
        "slug": "livestock-animals-goats",
        "nameEn": "Goats",
        "nameUr": "Goats"
      },
      {
        "slug": "livestock-animals-sheep",
        "nameEn": "Sheep",
        "nameUr": "Sheep"
      },
      {
        "slug": "livestock-animals-qurbani-animals",
        "nameEn": "Qurbani Animals",
        "nameUr": "Qurbani Animals"
      },
      {
        "slug": "livestock-animals-camels",
        "nameEn": "Camels",
        "nameUr": "Camels"
      },
      {
        "slug": "livestock-animals-horses",
        "nameEn": "Horses",
        "nameUr": "Horses"
      },
      {
        "slug": "livestock-animals-donkeys-mules",
        "nameEn": "Donkeys & Mules",
        "nameUr": "Donkeys & Mules"
      },
      {
        "slug": "livestock-animals-poultry",
        "nameEn": "Poultry (Desi & Broiler)",
        "nameUr": "Poultry (Desi & Broiler)"
      },
      {
        "slug": "livestock-animals-day-old-chicks",
        "nameEn": "Day-Old Chicks",
        "nameUr": "Day-Old Chicks"
      },
      {
        "slug": "livestock-animals-hatching-eggs",
        "nameEn": "Hatching Eggs",
        "nameUr": "Hatching Eggs"
      },
      {
        "slug": "livestock-animals-pigeons",
        "nameEn": "Pigeons",
        "nameUr": "Pigeons"
      },
      {
        "slug": "livestock-animals-ornamental-birds",
        "nameEn": "Ornamental Birds",
        "nameUr": "Ornamental Birds"
      },
      {
        "slug": "livestock-animals-fish-fingerlings",
        "nameEn": "Fish & Fingerlings",
        "nameUr": "Fish & Fingerlings"
      },
      {
        "slug": "livestock-animals-aquarium-supplies",
        "nameEn": "Aquarium & Supplies",
        "nameUr": "Aquarium & Supplies"
      },
      {
        "slug": "livestock-animals-dogs",
        "nameEn": "Dogs",
        "nameUr": "Dogs"
      },
      {
        "slug": "livestock-animals-cats",
        "nameEn": "Cats",
        "nameUr": "Cats"
      },
      {
        "slug": "livestock-animals-other-pets",
        "nameEn": "Other Pets",
        "nameUr": "Other Pets"
      },
      {
        "slug": "livestock-animals-animal-feed",
        "nameEn": "Animal Feed (Wanda, Silage, Bhoosa)",
        "nameUr": "Animal Feed (Wanda, Silage, Bhoosa)"
      },
      {
        "slug": "livestock-animals-veterinary-medicine-supplies",
        "nameEn": "Veterinary Medicine & Supplies",
        "nameUr": "Veterinary Medicine & Supplies"
      },
      {
        "slug": "livestock-animals-pet-food-accessories",
        "nameEn": "Pet Food & Accessories",
        "nameUr": "Pet Food & Accessories"
      },
      {
        "slug": "livestock-animals-other",
        "nameEn": "Other Livestock & Animals",
        "nameUr": "Other Livestock & Animals"
      }
    ]
  },
  {
    "slug": "fresh-produce-food",
    "nameEn": "Fresh Produce & Food",
    "nameUr": "تازہ پیداوار اور خوراک",
    "icon": "nutrition",
    "sort": 10,
    "subcategories": [
      {
        "slug": "fresh-produce-food-peaches",
        "nameEn": "Peaches",
        "nameUr": "Peaches"
      },
      {
        "slug": "fresh-produce-food-persimmon",
        "nameEn": "Persimmon (Amlok)",
        "nameUr": "Persimmon (Amlok)"
      },
      {
        "slug": "fresh-produce-food-citrus-malta",
        "nameEn": "Citrus & Malta",
        "nameUr": "Citrus & Malta"
      },
      {
        "slug": "fresh-produce-food-apples",
        "nameEn": "Apples",
        "nameUr": "Apples"
      },
      {
        "slug": "fresh-produce-food-apricots",
        "nameEn": "Apricots",
        "nameUr": "Apricots"
      },
      {
        "slug": "fresh-produce-food-plums",
        "nameEn": "Plums",
        "nameUr": "Plums"
      },
      {
        "slug": "fresh-produce-food-pears",
        "nameEn": "Pears",
        "nameUr": "Pears"
      },
      {
        "slug": "fresh-produce-food-grapes",
        "nameEn": "Grapes",
        "nameUr": "Grapes"
      },
      {
        "slug": "fresh-produce-food-loquat",
        "nameEn": "Loquat",
        "nameUr": "Loquat"
      },
      {
        "slug": "fresh-produce-food-pomegranate",
        "nameEn": "Pomegranate",
        "nameUr": "Pomegranate"
      },
      {
        "slug": "fresh-produce-food-guava",
        "nameEn": "Guava",
        "nameUr": "Guava"
      },
      {
        "slug": "fresh-produce-food-seasonal-fruit",
        "nameEn": "Seasonal Fruit (Other)",
        "nameUr": "Seasonal Fruit (Other)"
      },
      {
        "slug": "fresh-produce-food-vegetables",
        "nameEn": "Vegetables",
        "nameUr": "Vegetables"
      },
      {
        "slug": "fresh-produce-food-potato-onion-tomato",
        "nameEn": "Potato, Onion & Tomato",
        "nameUr": "Potato, Onion & Tomato"
      },
      {
        "slug": "fresh-produce-food-walnuts",
        "nameEn": "Walnuts",
        "nameUr": "Walnuts"
      },
      {
        "slug": "fresh-produce-food-almonds",
        "nameEn": "Almonds",
        "nameUr": "Almonds"
      },
      {
        "slug": "fresh-produce-food-pine-nuts",
        "nameEn": "Pine Nuts (Chilghoza)",
        "nameUr": "Pine Nuts (Chilghoza)"
      },
      {
        "slug": "fresh-produce-food-dried-figs-apricots",
        "nameEn": "Dried Figs & Apricots",
        "nameUr": "Dried Figs & Apricots"
      },
      {
        "slug": "fresh-produce-food-other-dry-fruits",
        "nameEn": "Other Dry Fruits",
        "nameUr": "Other Dry Fruits"
      },
      {
        "slug": "fresh-produce-food-honey",
        "nameEn": "Honey (Sidr, Palosa, Wild)",
        "nameUr": "Honey (Sidr, Palosa, Wild)"
      },
      {
        "slug": "fresh-produce-food-desi-ghee-butter",
        "nameEn": "Desi Ghee & Butter",
        "nameUr": "Desi Ghee & Butter"
      },
      {
        "slug": "fresh-produce-food-milk-dairy-products",
        "nameEn": "Milk & Dairy Products",
        "nameUr": "Milk & Dairy Products"
      },
      {
        "slug": "fresh-produce-food-wheat-flour",
        "nameEn": "Wheat & Flour",
        "nameUr": "Wheat & Flour"
      },
      {
        "slug": "fresh-produce-food-maize-rice",
        "nameEn": "Maize & Rice",
        "nameUr": "Maize & Rice"
      },
      {
        "slug": "fresh-produce-food-pulses-beans",
        "nameEn": "Pulses & Beans",
        "nameUr": "Pulses & Beans"
      },
      {
        "slug": "fresh-produce-food-cooking-oil",
        "nameEn": "Cooking Oil",
        "nameUr": "Cooking Oil"
      },
      {
        "slug": "fresh-produce-food-spices",
        "nameEn": "Spices",
        "nameUr": "Spices"
      },
      {
        "slug": "fresh-produce-food-tea-qehwa",
        "nameEn": "Tea & Qehwa",
        "nameUr": "Tea & Qehwa"
      },
      {
        "slug": "fresh-produce-food-olive-olive-oil",
        "nameEn": "Olive & Olive Oil",
        "nameUr": "Olive & Olive Oil"
      },
      {
        "slug": "fresh-produce-food-pickles-chutney-preserves",
        "nameEn": "Pickles, Chutney & Preserves",
        "nameUr": "Pickles, Chutney & Preserves"
      },
      {
        "slug": "fresh-produce-food-bakery-sweets",
        "nameEn": "Bakery & Sweets",
        "nameUr": "Bakery & Sweets"
      },
      {
        "slug": "fresh-produce-food-mushrooms",
        "nameEn": "Mushrooms",
        "nameUr": "Mushrooms"
      },
      {
        "slug": "fresh-produce-food-medicinal-herbs-plants",
        "nameEn": "Medicinal Herbs & Plants",
        "nameUr": "Medicinal Herbs & Plants"
      },
      {
        "slug": "fresh-produce-food-organic-produce",
        "nameEn": "Organic Produce",
        "nameUr": "Organic Produce"
      },
      {
        "slug": "fresh-produce-food-other",
        "nameEn": "Other Food Items",
        "nameUr": "Other Food Items"
      }
    ]
  },
  {
    "slug": "handicrafts-artisan-goods",
    "nameEn": "Handicrafts & Artisan Goods",
    "nameUr": "دستکاری",
    "icon": "handyman",
    "sort": 11,
    "subcategories": [
      {
        "slug": "handicrafts-artisan-goods-swat-woodcraft-carved-furniture",
        "nameEn": "Swat Woodcraft & Carved Furniture",
        "nameUr": "Swat Woodcraft & Carved Furniture"
      },
      {
        "slug": "handicrafts-artisan-goods-hand-embroidery-needlework",
        "nameEn": "Hand Embroidery & Needlework",
        "nameUr": "Hand Embroidery & Needlework"
      },
      {
        "slug": "handicrafts-artisan-goods-embroidered-dresses",
        "nameEn": "Embroidered Dresses",
        "nameUr": "Embroidered Dresses"
      },
      {
        "slug": "handicrafts-artisan-goods-truck-art-painted-goods",
        "nameEn": "Truck Art & Painted Goods",
        "nameUr": "Truck Art & Painted Goods"
      },
      {
        "slug": "handicrafts-artisan-goods-pottery-clay-work",
        "nameEn": "Pottery & Clay Work",
        "nameUr": "Pottery & Clay Work"
      },
      {
        "slug": "handicrafts-artisan-goods-copper-brassware",
        "nameEn": "Copper & Brassware",
        "nameUr": "Copper & Brassware"
      },
      {
        "slug": "handicrafts-artisan-goods-marble-stone-crafts",
        "nameEn": "Marble & Stone Crafts",
        "nameUr": "Marble & Stone Crafts"
      },
      {
        "slug": "handicrafts-artisan-goods-handmade-jewellery",
        "nameEn": "Handmade Jewellery",
        "nameUr": "Handmade Jewellery"
      },
      {
        "slug": "handicrafts-artisan-goods-handwoven-rugs-gabba-namda",
        "nameEn": "Handwoven Rugs, Gabba & Namda",
        "nameUr": "Handwoven Rugs, Gabba & Namda"
      },
      {
        "slug": "handicrafts-artisan-goods-shawls",
        "nameEn": "Shawls (Pashmina, Dhussa, Chitrali)",
        "nameUr": "Shawls (Pashmina, Dhussa, Chitrali)"
      },
      {
        "slug": "handicrafts-artisan-goods-chappals",
        "nameEn": "Chappals (Peshawari, Charsadda, Norozi, Kaptaan)",
        "nameUr": "Chappals (Peshawari, Charsadda, Norozi, Kaptaan)"
      },
      {
        "slug": "handicrafts-artisan-goods-cane-bamboo-basketry",
        "nameEn": "Cane, Bamboo & Basketry",
        "nameUr": "Cane, Bamboo & Basketry"
      },
      {
        "slug": "handicrafts-artisan-goods-woollen-knitwear",
        "nameEn": "Woollen Knitwear",
        "nameUr": "Woollen Knitwear"
      },
      {
        "slug": "handicrafts-artisan-goods-leathercraft",
        "nameEn": "Leathercraft",
        "nameUr": "Leathercraft"
      },
      {
        "slug": "handicrafts-artisan-goods-calligraphy-islamic-art",
        "nameEn": "Calligraphy & Islamic Art",
        "nameUr": "Calligraphy & Islamic Art"
      },
      {
        "slug": "handicrafts-artisan-goods-paintings-artwork",
        "nameEn": "Paintings & Artwork",
        "nameUr": "Paintings & Artwork"
      },
      {
        "slug": "handicrafts-artisan-goods-traditional-musical-instruments",
        "nameEn": "Traditional Musical Instruments (Rabab, Mangey)",
        "nameUr": "Traditional Musical Instruments (Rabab, Mangey)"
      },
      {
        "slug": "handicrafts-artisan-goods-antiques-collectibles",
        "nameEn": "Antiques & Collectibles",
        "nameUr": "Antiques & Collectibles"
      },
      {
        "slug": "handicrafts-artisan-goods-other",
        "nameEn": "Other Handmade Items",
        "nameUr": "Other Handmade Items"
      }
    ]
  },
  {
    "slug": "furniture-home-decor",
    "nameEn": "Furniture & Home Decor",
    "nameUr": "فرنیچر اور گھر کی سجاوٹ",
    "icon": "chair",
    "sort": 12,
    "subcategories": [
      {
        "slug": "furniture-home-decor-beds-bed-sets",
        "nameEn": "Beds & Bed Sets",
        "nameUr": "Beds & Bed Sets"
      },
      {
        "slug": "furniture-home-decor-sofas-sofa-sets",
        "nameEn": "Sofas & Sofa Sets",
        "nameUr": "Sofas & Sofa Sets"
      },
      {
        "slug": "furniture-home-decor-chairs-stools",
        "nameEn": "Chairs & Stools",
        "nameUr": "Chairs & Stools"
      },
      {
        "slug": "furniture-home-decor-tables-dining-sets",
        "nameEn": "Tables & Dining Sets",
        "nameUr": "Tables & Dining Sets"
      },
      {
        "slug": "furniture-home-decor-wardrobes-almari",
        "nameEn": "Wardrobes & Almari",
        "nameUr": "Wardrobes & Almari"
      },
      {
        "slug": "furniture-home-decor-dressing-tables",
        "nameEn": "Dressing Tables",
        "nameUr": "Dressing Tables"
      },
      {
        "slug": "furniture-home-decor-office-furniture",
        "nameEn": "Office Furniture",
        "nameUr": "Office Furniture"
      },
      {
        "slug": "furniture-home-decor-outdoor-garden-furniture",
        "nameEn": "Outdoor & Garden Furniture",
        "nameUr": "Outdoor & Garden Furniture"
      },
      {
        "slug": "furniture-home-decor-kitchen-cabinets",
        "nameEn": "Kitchen Cabinets",
        "nameUr": "Kitchen Cabinets"
      },
      {
        "slug": "furniture-home-decor-mattresses-pillows",
        "nameEn": "Mattresses & Pillows",
        "nameUr": "Mattresses & Pillows"
      },
      {
        "slug": "furniture-home-decor-curtains-blinds",
        "nameEn": "Curtains & Blinds",
        "nameUr": "Curtains & Blinds"
      },
      {
        "slug": "furniture-home-decor-carpets-rugs",
        "nameEn": "Carpets & Rugs",
        "nameUr": "Carpets & Rugs"
      },
      {
        "slug": "furniture-home-decor-wall-decor-frames",
        "nameEn": "Wall Decor & Frames",
        "nameUr": "Wall Decor & Frames"
      },
      {
        "slug": "furniture-home-decor-lighting-chandeliers",
        "nameEn": "Lighting & Chandeliers",
        "nameUr": "Lighting & Chandeliers"
      },
      {
        "slug": "furniture-home-decor-mirrors",
        "nameEn": "Mirrors",
        "nameUr": "Mirrors"
      },
      {
        "slug": "furniture-home-decor-bedsheets-quilts-razai",
        "nameEn": "Bedsheets, Quilts & Razai",
        "nameUr": "Bedsheets, Quilts & Razai"
      },
      {
        "slug": "furniture-home-decor-crockery-kitchenware",
        "nameEn": "Crockery & Kitchenware",
        "nameUr": "Crockery & Kitchenware"
      },
      {
        "slug": "furniture-home-decor-storage-racks-shelving",
        "nameEn": "Storage, Racks & Shelving",
        "nameUr": "Storage, Racks & Shelving"
      },
      {
        "slug": "furniture-home-decor-other",
        "nameEn": "Other Furniture",
        "nameUr": "Other Furniture"
      }
    ]
  },
  {
    "slug": "clothing-fashion",
    "nameEn": "Clothing & Fashion",
    "nameUr": "کپڑے اور فیشن",
    "icon": "checkroom",
    "sort": 13,
    "subcategories": [
      {
        "slug": "clothing-fashion-men-s-clothing",
        "nameEn": "Men's Clothing",
        "nameUr": "Men's Clothing"
      },
      {
        "slug": "clothing-fashion-women-s-clothing",
        "nameEn": "Women's Clothing",
        "nameUr": "Women's Clothing"
      },
      {
        "slug": "clothing-fashion-kids-clothing",
        "nameEn": "Kids' Clothing",
        "nameUr": "Kids' Clothing"
      },
      {
        "slug": "clothing-fashion-unstitched-fabric-suit-lengths",
        "nameEn": "Unstitched Fabric & Suit Lengths",
        "nameUr": "Unstitched Fabric & Suit Lengths"
      },
      {
        "slug": "clothing-fashion-wedding-bridal-wear",
        "nameEn": "Wedding & Bridal Wear",
        "nameUr": "Wedding & Bridal Wear"
      },
      {
        "slug": "clothing-fashion-traditional-cultural-wear",
        "nameEn": "Traditional & Cultural Wear",
        "nameUr": "Traditional & Cultural Wear"
      },
      {
        "slug": "clothing-fashion-winter-wear-jackets",
        "nameEn": "Winter Wear & Jackets",
        "nameUr": "Winter Wear & Jackets"
      },
      {
        "slug": "clothing-fashion-shawls-dupattas",
        "nameEn": "Shawls & Dupattas",
        "nameUr": "Shawls & Dupattas"
      },
      {
        "slug": "clothing-fashion-caps-turbans",
        "nameEn": "Caps & Turbans (Pakol, Kufi)",
        "nameUr": "Caps & Turbans (Pakol, Kufi)"
      },
      {
        "slug": "clothing-fashion-men-s-footwear",
        "nameEn": "Men's Footwear",
        "nameUr": "Men's Footwear"
      },
      {
        "slug": "clothing-fashion-women-s-footwear",
        "nameEn": "Women's Footwear",
        "nameUr": "Women's Footwear"
      },
      {
        "slug": "clothing-fashion-kids-footwear",
        "nameEn": "Kids' Footwear",
        "nameUr": "Kids' Footwear"
      },
      {
        "slug": "clothing-fashion-bags-purses-luggage",
        "nameEn": "Bags, Purses & Luggage",
        "nameUr": "Bags, Purses & Luggage"
      },
      {
        "slug": "clothing-fashion-watches",
        "nameEn": "Watches",
        "nameUr": "Watches"
      },
      {
        "slug": "clothing-fashion-gold-silver-jewellery",
        "nameEn": "Gold & Silver Jewellery",
        "nameUr": "Gold & Silver Jewellery"
      },
      {
        "slug": "clothing-fashion-artificial-jewellery",
        "nameEn": "Artificial Jewellery",
        "nameUr": "Artificial Jewellery"
      },
      {
        "slug": "clothing-fashion-sunglasses-optics",
        "nameEn": "Sunglasses & Optics",
        "nameUr": "Sunglasses & Optics"
      },
      {
        "slug": "clothing-fashion-cosmetics-perfumes",
        "nameEn": "Cosmetics & Perfumes",
        "nameUr": "Cosmetics & Perfumes"
      },
      {
        "slug": "clothing-fashion-tailoring-fabric-accessories",
        "nameEn": "Tailoring Fabric & Accessories",
        "nameUr": "Tailoring Fabric & Accessories"
      },
      {
        "slug": "clothing-fashion-other",
        "nameEn": "Other Fashion Items",
        "nameUr": "Other Fashion Items"
      }
    ]
  },
  {
    "slug": "construction-building-materials",
    "nameEn": "Construction & Building Materials",
    "nameUr": "تعمیراتی سامان",
    "icon": "construction",
    "sort": 14,
    "subcategories": [
      {
        "slug": "construction-building-materials-cement",
        "nameEn": "Cement",
        "nameUr": "Cement"
      },
      {
        "slug": "construction-building-materials-steel-sariya",
        "nameEn": "Steel & Sariya",
        "nameUr": "Steel & Sariya"
      },
      {
        "slug": "construction-building-materials-bricks-blocks",
        "nameEn": "Bricks & Blocks",
        "nameUr": "Bricks & Blocks"
      },
      {
        "slug": "construction-building-materials-sand-gravel-crush",
        "nameEn": "Sand, Gravel & Crush",
        "nameUr": "Sand, Gravel & Crush"
      },
      {
        "slug": "construction-building-materials-marble-granite-tiles",
        "nameEn": "Marble, Granite & Tiles",
        "nameUr": "Marble, Granite & Tiles"
      },
      {
        "slug": "construction-building-materials-timber-wood",
        "nameEn": "Timber & Wood",
        "nameUr": "Timber & Wood"
      },
      {
        "slug": "construction-building-materials-doors-windows",
        "nameEn": "Doors & Windows",
        "nameUr": "Doors & Windows"
      },
      {
        "slug": "construction-building-materials-sanitary-bathroom-ware",
        "nameEn": "Sanitary & Bathroom Ware",
        "nameUr": "Sanitary & Bathroom Ware"
      },
      {
        "slug": "construction-building-materials-paints-coatings",
        "nameEn": "Paints & Coatings",
        "nameUr": "Paints & Coatings"
      },
      {
        "slug": "construction-building-materials-electrical-wiring-fittings",
        "nameEn": "Electrical Wiring & Fittings",
        "nameUr": "Electrical Wiring & Fittings"
      },
      {
        "slug": "construction-building-materials-pipes-fittings",
        "nameEn": "Pipes & Fittings",
        "nameUr": "Pipes & Fittings"
      },
      {
        "slug": "construction-building-materials-roofing-sheets",
        "nameEn": "Roofing & Sheets",
        "nameUr": "Roofing & Sheets"
      },
      {
        "slug": "construction-building-materials-glass-aluminium-work",
        "nameEn": "Glass & Aluminium Work",
        "nameUr": "Glass & Aluminium Work"
      },
      {
        "slug": "construction-building-materials-hardware-fasteners",
        "nameEn": "Hardware & Fasteners",
        "nameUr": "Hardware & Fasteners"
      },
      {
        "slug": "construction-building-materials-insulation-waterproofing",
        "nameEn": "Insulation & Waterproofing",
        "nameUr": "Insulation & Waterproofing"
      },
      {
        "slug": "construction-building-materials-prefab-container-structures",
        "nameEn": "Prefab & Container Structures",
        "nameUr": "Prefab & Container Structures"
      },
      {
        "slug": "construction-building-materials-scaffolding-shuttering",
        "nameEn": "Scaffolding & Shuttering",
        "nameUr": "Scaffolding & Shuttering"
      },
      {
        "slug": "construction-building-materials-other",
        "nameEn": "Other Building Materials",
        "nameUr": "Other Building Materials"
      }
    ]
  },
  {
    "slug": "tools-industrial-machinery",
    "nameEn": "Tools & Industrial Machinery",
    "nameUr": "اوزار اور مشینری",
    "icon": "precision_manufacturing",
    "sort": 15,
    "subcategories": [
      {
        "slug": "tools-industrial-machinery-power-tools",
        "nameEn": "Power Tools",
        "nameUr": "Power Tools"
      },
      {
        "slug": "tools-industrial-machinery-hand-tools",
        "nameEn": "Hand Tools",
        "nameUr": "Hand Tools"
      },
      {
        "slug": "tools-industrial-machinery-welding-equipment",
        "nameEn": "Welding Equipment",
        "nameUr": "Welding Equipment"
      },
      {
        "slug": "tools-industrial-machinery-workshop-machinery",
        "nameEn": "Workshop Machinery (Lathe, Drill)",
        "nameUr": "Workshop Machinery (Lathe, Drill)"
      },
      {
        "slug": "tools-industrial-machinery-air-compressors",
        "nameEn": "Air Compressors",
        "nameUr": "Air Compressors"
      },
      {
        "slug": "tools-industrial-machinery-water-pumps-motors",
        "nameEn": "Water Pumps & Motors",
        "nameUr": "Water Pumps & Motors"
      },
      {
        "slug": "tools-industrial-machinery-flour-mills-chakki",
        "nameEn": "Flour Mills & Chakki",
        "nameUr": "Flour Mills & Chakki"
      },
      {
        "slug": "tools-industrial-machinery-marble-stone-cutting-machines",
        "nameEn": "Marble & Stone Cutting Machines",
        "nameUr": "Marble & Stone Cutting Machines"
      },
      {
        "slug": "tools-industrial-machinery-crush-plants",
        "nameEn": "Crush Plants",
        "nameUr": "Crush Plants"
      },
      {
        "slug": "tools-industrial-machinery-excavators-loaders-dumpers",
        "nameEn": "Excavators, Loaders & Dumpers",
        "nameUr": "Excavators, Loaders & Dumpers"
      },
      {
        "slug": "tools-industrial-machinery-forklifts-cranes",
        "nameEn": "Forklifts & Cranes",
        "nameUr": "Forklifts & Cranes"
      },
      {
        "slug": "tools-industrial-machinery-ice-factory-cold-chain-equipment",
        "nameEn": "Ice Factory & Cold Chain Equipment",
        "nameUr": "Ice Factory & Cold Chain Equipment"
      },
      {
        "slug": "tools-industrial-machinery-packaging-machines",
        "nameEn": "Packaging Machines",
        "nameUr": "Packaging Machines"
      },
      {
        "slug": "tools-industrial-machinery-weighing-scales",
        "nameEn": "Weighing Scales",
        "nameUr": "Weighing Scales"
      },
      {
        "slug": "tools-industrial-machinery-industrial-spare-parts",
        "nameEn": "Industrial Spare Parts",
        "nameUr": "Industrial Spare Parts"
      },
      {
        "slug": "tools-industrial-machinery-safety-equipment",
        "nameEn": "Safety Equipment",
        "nameUr": "Safety Equipment"
      },
      {
        "slug": "tools-industrial-machinery-other",
        "nameEn": "Other Machinery",
        "nameUr": "Other Machinery"
      }
    ]
  },
  {
    "slug": "business-shops-equipment",
    "nameEn": "Business, Shops & Equipment",
    "nameUr": "کاروبار اور دکان کا سامان",
    "icon": "storefront",
    "sort": 16,
    "subcategories": [
      {
        "slug": "business-shops-equipment-running-business-for-sale",
        "nameEn": "Running Business for Sale",
        "nameUr": "Running Business for Sale"
      },
      {
        "slug": "business-shops-equipment-shop-fittings-fixtures",
        "nameEn": "Shop Fittings & Fixtures",
        "nameUr": "Shop Fittings & Fixtures"
      },
      {
        "slug": "business-shops-equipment-display-racks-counters",
        "nameEn": "Display Racks & Counters",
        "nameUr": "Display Racks & Counters"
      },
      {
        "slug": "business-shops-equipment-restaurant-hotel-equipment",
        "nameEn": "Restaurant & Hotel Equipment",
        "nameUr": "Restaurant & Hotel Equipment"
      },
      {
        "slug": "business-shops-equipment-bakery-equipment",
        "nameEn": "Bakery Equipment",
        "nameUr": "Bakery Equipment"
      },
      {
        "slug": "business-shops-equipment-salon-barber-equipment",
        "nameEn": "Salon & Barber Equipment",
        "nameUr": "Salon & Barber Equipment"
      },
      {
        "slug": "business-shops-equipment-clinic-medical-equipment",
        "nameEn": "Clinic & Medical Equipment",
        "nameUr": "Clinic & Medical Equipment"
      },
      {
        "slug": "business-shops-equipment-gym-equipment-for-business",
        "nameEn": "Gym Equipment for Business",
        "nameUr": "Gym Equipment for Business"
      },
      {
        "slug": "business-shops-equipment-office-equipment",
        "nameEn": "Office Equipment",
        "nameUr": "Office Equipment"
      },
      {
        "slug": "business-shops-equipment-stock-clearance-wholesale-lots",
        "nameEn": "Stock Clearance & Wholesale Lots",
        "nameUr": "Stock Clearance & Wholesale Lots"
      },
      {
        "slug": "business-shops-equipment-dealership-distribution-offers",
        "nameEn": "Dealership & Distribution Offers",
        "nameUr": "Dealership & Distribution Offers"
      },
      {
        "slug": "business-shops-equipment-franchise-opportunities",
        "nameEn": "Franchise Opportunities",
        "nameUr": "Franchise Opportunities"
      },
      {
        "slug": "business-shops-equipment-other",
        "nameEn": "Other Business Items",
        "nameUr": "Other Business Items"
      }
    ]
  },
  {
    "slug": "wholesale-bulk-supply",
    "nameEn": "Wholesale & Bulk Supply",
    "nameUr": "ہول سیل",
    "icon": "inventory",
    "sort": 17,
    "subcategories": [
      {
        "slug": "wholesale-bulk-supply-bulk-fruit-crates",
        "nameEn": "Bulk Fruit & Crates",
        "nameUr": "Bulk Fruit & Crates"
      },
      {
        "slug": "wholesale-bulk-supply-bulk-vegetables",
        "nameEn": "Bulk Vegetables",
        "nameUr": "Bulk Vegetables"
      },
      {
        "slug": "wholesale-bulk-supply-grain-flour-in-bulk",
        "nameEn": "Grain & Flour in Bulk",
        "nameUr": "Grain & Flour in Bulk"
      },
      {
        "slug": "wholesale-bulk-supply-cloth-bales",
        "nameEn": "Cloth Bales",
        "nameUr": "Cloth Bales"
      },
      {
        "slug": "wholesale-bulk-supply-hardware-lots",
        "nameEn": "Hardware Lots",
        "nameUr": "Hardware Lots"
      },
      {
        "slug": "wholesale-bulk-supply-general-trading-import",
        "nameEn": "General Trading & Import",
        "nameUr": "General Trading & Import"
      },
      {
        "slug": "wholesale-bulk-supply-packaging-materials-in-bulk",
        "nameEn": "Packaging Materials in Bulk",
        "nameUr": "Packaging Materials in Bulk"
      },
      {
        "slug": "wholesale-bulk-supply-distributor-enquiries",
        "nameEn": "Distributor Enquiries",
        "nameUr": "Distributor Enquiries"
      },
      {
        "slug": "wholesale-bulk-supply-other",
        "nameEn": "Other Wholesale",
        "nameUr": "Other Wholesale"
      }
    ]
  },
  {
    "slug": "services",
    "nameEn": "Services",
    "nameUr": "خدمات",
    "icon": "home_repair_service",
    "sort": 18,
    "subcategories": [
      {
        "slug": "services-construction-contractors",
        "nameEn": "Construction & Contractors",
        "nameUr": "Construction & Contractors"
      },
      {
        "slug": "services-mason",
        "nameEn": "Mason (Mistri)",
        "nameUr": "Mason (Mistri)"
      },
      {
        "slug": "services-carpenter",
        "nameEn": "Carpenter",
        "nameUr": "Carpenter"
      },
      {
        "slug": "services-electrician",
        "nameEn": "Electrician",
        "nameUr": "Electrician"
      },
      {
        "slug": "services-plumber",
        "nameEn": "Plumber",
        "nameUr": "Plumber"
      },
      {
        "slug": "services-painter",
        "nameEn": "Painter",
        "nameUr": "Painter"
      },
      {
        "slug": "services-welder-fabricator",
        "nameEn": "Welder & Fabricator",
        "nameUr": "Welder & Fabricator"
      },
      {
        "slug": "services-solar-installation",
        "nameEn": "Solar Installation",
        "nameUr": "Solar Installation"
      },
      {
        "slug": "services-ac-appliance-repair",
        "nameEn": "AC & Appliance Repair",
        "nameUr": "AC & Appliance Repair"
      },
      {
        "slug": "services-mobile-computer-repair",
        "nameEn": "Mobile & Computer Repair",
        "nameUr": "Mobile & Computer Repair"
      },
      {
        "slug": "services-auto-mechanic-denting-painting",
        "nameEn": "Auto Mechanic, Denting & Painting",
        "nameUr": "Auto Mechanic, Denting & Painting"
      },
      {
        "slug": "services-transport-goods-delivery",
        "nameEn": "Transport & Goods Delivery",
        "nameUr": "Transport & Goods Delivery"
      },
      {
        "slug": "services-movers-packers",
        "nameEn": "Movers & Packers",
        "nameUr": "Movers & Packers"
      },
      {
        "slug": "services-car-van-rental",
        "nameEn": "Car & Van Rental",
        "nameUr": "Car & Van Rental"
      },
      {
        "slug": "services-tractor-machinery-rental",
        "nameEn": "Tractor & Machinery Rental",
        "nameUr": "Tractor & Machinery Rental"
      },
      {
        "slug": "services-water-tanker-supply",
        "nameEn": "Water Tanker Supply",
        "nameUr": "Water Tanker Supply"
      },
      {
        "slug": "services-borewell-tubewell-drilling",
        "nameEn": "Borewell & Tubewell Drilling",
        "nameUr": "Borewell & Tubewell Drilling"
      },
      {
        "slug": "services-catering-cooks",
        "nameEn": "Catering & Cooks",
        "nameUr": "Catering & Cooks"
      },
      {
        "slug": "services-marriage-hall-event-services",
        "nameEn": "Marriage Hall & Event Services",
        "nameUr": "Marriage Hall & Event Services"
      },
      {
        "slug": "services-photography-videography",
        "nameEn": "Photography & Videography",
        "nameUr": "Photography & Videography"
      },
      {
        "slug": "services-printing-flex-advertising",
        "nameEn": "Printing, Flex & Advertising",
        "nameUr": "Printing, Flex & Advertising"
      },
      {
        "slug": "services-tailoring-stitching",
        "nameEn": "Tailoring & Stitching",
        "nameUr": "Tailoring & Stitching"
      },
      {
        "slug": "services-beauty-salon",
        "nameEn": "Beauty & Salon",
        "nameUr": "Beauty & Salon"
      },
      {
        "slug": "services-tutoring-academies",
        "nameEn": "Tutoring & Academies",
        "nameUr": "Tutoring & Academies"
      },
      {
        "slug": "services-it-computer-services",
        "nameEn": "IT & Computer Services",
        "nameUr": "IT & Computer Services"
      },
      {
        "slug": "services-web-graphic-design",
        "nameEn": "Web & Graphic Design",
        "nameUr": "Web & Graphic Design"
      },
      {
        "slug": "services-legal-documentation",
        "nameEn": "Legal & Documentation",
        "nameUr": "Legal & Documentation"
      },
      {
        "slug": "services-accounting-tax",
        "nameEn": "Accounting & Tax",
        "nameUr": "Accounting & Tax"
      },
      {
        "slug": "services-travel-hajj-umrah",
        "nameEn": "Travel, Hajj & Umrah",
        "nameUr": "Travel, Hajj & Umrah"
      },
      {
        "slug": "services-visa-overseas-consultancy",
        "nameEn": "Visa & Overseas Consultancy",
        "nameUr": "Visa & Overseas Consultancy"
      },
      {
        "slug": "services-courier-cargo",
        "nameEn": "Courier & Cargo",
        "nameUr": "Courier & Cargo"
      },
      {
        "slug": "services-security-guards",
        "nameEn": "Security Guards",
        "nameUr": "Security Guards"
      },
      {
        "slug": "services-cleaning-housekeeping",
        "nameEn": "Cleaning & Housekeeping",
        "nameUr": "Cleaning & Housekeeping"
      },
      {
        "slug": "services-pest-control",
        "nameEn": "Pest Control",
        "nameUr": "Pest Control"
      },
      {
        "slug": "services-land-survey-measurement",
        "nameEn": "Land Survey & Measurement",
        "nameUr": "Land Survey & Measurement"
      },
      {
        "slug": "services-veterinary-services",
        "nameEn": "Veterinary Services",
        "nameUr": "Veterinary Services"
      },
      {
        "slug": "services-agricultural-consultancy",
        "nameEn": "Agricultural Consultancy",
        "nameUr": "Agricultural Consultancy"
      },
      {
        "slug": "services-laundry-dry-cleaning",
        "nameEn": "Laundry & Dry Cleaning",
        "nameUr": "Laundry & Dry Cleaning"
      },
      {
        "slug": "services-gas-cylinder-refill",
        "nameEn": "Gas & Cylinder Refill",
        "nameUr": "Gas & Cylinder Refill"
      },
      {
        "slug": "services-other",
        "nameEn": "Other Services",
        "nameUr": "Other Services"
      }
    ]
  },
  {
    "slug": "jobs",
    "nameEn": "Jobs",
    "nameUr": "ملازمتیں",
    "icon": "work",
    "sort": 19,
    "subcategories": [
      {
        "slug": "jobs-full-time-jobs",
        "nameEn": "Full-Time Jobs",
        "nameUr": "Full-Time Jobs"
      },
      {
        "slug": "jobs-part-time-jobs",
        "nameEn": "Part-Time Jobs",
        "nameUr": "Part-Time Jobs"
      },
      {
        "slug": "jobs-daily-wage-labour",
        "nameEn": "Daily Wage & Labour",
        "nameUr": "Daily Wage & Labour"
      },
      {
        "slug": "jobs-sales-marketing",
        "nameEn": "Sales & Marketing",
        "nameUr": "Sales & Marketing"
      },
      {
        "slug": "jobs-drivers",
        "nameEn": "Drivers",
        "nameUr": "Drivers"
      },
      {
        "slug": "jobs-teaching-education",
        "nameEn": "Teaching & Education",
        "nameUr": "Teaching & Education"
      },
      {
        "slug": "jobs-healthcare-medical",
        "nameEn": "Healthcare & Medical",
        "nameUr": "Healthcare & Medical"
      },
      {
        "slug": "jobs-engineering",
        "nameEn": "Engineering",
        "nameUr": "Engineering"
      },
      {
        "slug": "jobs-it-software",
        "nameEn": "IT & Software",
        "nameUr": "IT & Software"
      },
      {
        "slug": "jobs-accounting-finance",
        "nameEn": "Accounting & Finance",
        "nameUr": "Accounting & Finance"
      },
      {
        "slug": "jobs-construction-labour",
        "nameEn": "Construction Labour",
        "nameUr": "Construction Labour"
      },
      {
        "slug": "jobs-farm-agriculture-labour",
        "nameEn": "Farm & Agriculture Labour",
        "nameUr": "Farm & Agriculture Labour"
      },
      {
        "slug": "jobs-shop-assistant-retail",
        "nameEn": "Shop Assistant & Retail",
        "nameUr": "Shop Assistant & Retail"
      },
      {
        "slug": "jobs-security-staff",
        "nameEn": "Security Staff",
        "nameUr": "Security Staff"
      },
      {
        "slug": "jobs-domestic-help",
        "nameEn": "Domestic Help",
        "nameUr": "Domestic Help"
      },
      {
        "slug": "jobs-office-administration",
        "nameEn": "Office Administration",
        "nameUr": "Office Administration"
      },
      {
        "slug": "jobs-hotel-restaurant-staff",
        "nameEn": "Hotel & Restaurant Staff",
        "nameUr": "Hotel & Restaurant Staff"
      },
      {
        "slug": "jobs-internships-training",
        "nameEn": "Internships & Training",
        "nameUr": "Internships & Training"
      },
      {
        "slug": "jobs-online-remote-work",
        "nameEn": "Online & Remote Work",
        "nameUr": "Online & Remote Work"
      },
      {
        "slug": "jobs-overseas-jobs",
        "nameEn": "Overseas Jobs",
        "nameUr": "Overseas Jobs"
      },
      {
        "slug": "jobs-jobs-wanted",
        "nameEn": "Jobs Wanted (Candidate Profiles)",
        "nameUr": "Jobs Wanted (Candidate Profiles)"
      },
      {
        "slug": "jobs-other",
        "nameEn": "Other Jobs",
        "nameUr": "Other Jobs"
      }
    ]
  },
  {
    "slug": "education-stationery",
    "nameEn": "Education & Stationery",
    "nameUr": "تعلیم اور اسٹیشنری",
    "icon": "school",
    "sort": 20,
    "subcategories": [
      {
        "slug": "education-stationery-textbooks-course-books",
        "nameEn": "Textbooks & Course Books",
        "nameUr": "Textbooks & Course Books"
      },
      {
        "slug": "education-stationery-islamic-religious-books",
        "nameEn": "Islamic & Religious Books",
        "nameUr": "Islamic & Religious Books"
      },
      {
        "slug": "education-stationery-novels-literature",
        "nameEn": "Novels & Literature",
        "nameUr": "Novels & Literature"
      },
      {
        "slug": "education-stationery-reference-competitive-exam-books",
        "nameEn": "Reference & Competitive Exam Books",
        "nameUr": "Reference & Competitive Exam Books"
      },
      {
        "slug": "education-stationery-stationery-office-supplies",
        "nameEn": "Stationery & Office Supplies",
        "nameUr": "Stationery & Office Supplies"
      },
      {
        "slug": "education-stationery-school-uniforms-bags",
        "nameEn": "School Uniforms & Bags",
        "nameUr": "School Uniforms & Bags"
      },
      {
        "slug": "education-stationery-lab-science-equipment",
        "nameEn": "Lab & Science Equipment",
        "nameUr": "Lab & Science Equipment"
      },
      {
        "slug": "education-stationery-educational-toys",
        "nameEn": "Educational Toys",
        "nameUr": "Educational Toys"
      },
      {
        "slug": "education-stationery-online-courses-material",
        "nameEn": "Online Courses & Material",
        "nameUr": "Online Courses & Material"
      },
      {
        "slug": "education-stationery-school-furniture",
        "nameEn": "School Furniture",
        "nameUr": "School Furniture"
      },
      {
        "slug": "education-stationery-other",
        "nameEn": "Other Educational Items",
        "nameUr": "Other Educational Items"
      }
    ]
  },
  {
    "slug": "health-beauty",
    "nameEn": "Health & Beauty",
    "nameUr": "صحت اور خوبصورتی",
    "icon": "health_and_safety",
    "sort": 21,
    "subcategories": [
      {
        "slug": "health-beauty-medical-equipment",
        "nameEn": "Medical Equipment (Wheelchair, Oxygen, Nebulizer)",
        "nameUr": "Medical Equipment (Wheelchair, Oxygen, Nebulizer)"
      },
      {
        "slug": "health-beauty-bp-sugar-monitors",
        "nameEn": "BP & Sugar Monitors",
        "nameUr": "BP & Sugar Monitors"
      },
      {
        "slug": "health-beauty-hospital-furniture",
        "nameEn": "Hospital Furniture",
        "nameUr": "Hospital Furniture"
      },
      {
        "slug": "health-beauty-herbal-unani-products",
        "nameEn": "Herbal & Unani Products",
        "nameUr": "Herbal & Unani Products"
      },
      {
        "slug": "health-beauty-fitness-supplements",
        "nameEn": "Fitness Supplements",
        "nameUr": "Fitness Supplements"
      },
      {
        "slug": "health-beauty-skincare-products",
        "nameEn": "Skincare Products",
        "nameUr": "Skincare Products"
      },
      {
        "slug": "health-beauty-hair-care-products",
        "nameEn": "Hair Care Products",
        "nameUr": "Hair Care Products"
      },
      {
        "slug": "health-beauty-baby-care-products",
        "nameEn": "Baby Care Products",
        "nameUr": "Baby Care Products"
      },
      {
        "slug": "health-beauty-personal-care-devices",
        "nameEn": "Personal Care Devices",
        "nameUr": "Personal Care Devices"
      },
      {
        "slug": "health-beauty-optical-eyewear",
        "nameEn": "Optical & Eyewear",
        "nameUr": "Optical & Eyewear"
      },
      {
        "slug": "health-beauty-hearing-aids",
        "nameEn": "Hearing Aids",
        "nameUr": "Hearing Aids"
      },
      {
        "slug": "health-beauty-medical-consumables-supplies",
        "nameEn": "Medical Consumables & Supplies",
        "nameUr": "Medical Consumables & Supplies"
      },
      {
        "slug": "health-beauty-other",
        "nameEn": "Other Health Items",
        "nameUr": "Other Health Items"
      }
    ]
  },
  {
    "slug": "sports-outdoor",
    "nameEn": "Sports & Outdoor",
    "nameUr": "کھیل اور تفریح",
    "icon": "sports_soccer",
    "sort": 22,
    "subcategories": [
      {
        "slug": "sports-outdoor-cricket-gear",
        "nameEn": "Cricket Gear",
        "nameUr": "Cricket Gear"
      },
      {
        "slug": "sports-outdoor-football-futsal",
        "nameEn": "Football & Futsal",
        "nameUr": "Football & Futsal"
      },
      {
        "slug": "sports-outdoor-volleyball",
        "nameEn": "Volleyball",
        "nameUr": "Volleyball"
      },
      {
        "slug": "sports-outdoor-badminton-racket-sports",
        "nameEn": "Badminton & Racket Sports",
        "nameUr": "Badminton & Racket Sports"
      },
      {
        "slug": "sports-outdoor-gym-fitness-equipment",
        "nameEn": "Gym & Fitness Equipment",
        "nameUr": "Gym & Fitness Equipment"
      },
      {
        "slug": "sports-outdoor-sports-bicycles",
        "nameEn": "Sports Bicycles",
        "nameUr": "Sports Bicycles"
      },
      {
        "slug": "sports-outdoor-fishing-gear",
        "nameEn": "Fishing Gear",
        "nameUr": "Fishing Gear"
      },
      {
        "slug": "sports-outdoor-camping-hiking-gear",
        "nameEn": "Camping & Hiking Gear",
        "nameUr": "Camping & Hiking Gear"
      },
      {
        "slug": "sports-outdoor-tents-shamiana",
        "nameEn": "Tents & Shamiana",
        "nameUr": "Tents & Shamiana"
      },
      {
        "slug": "sports-outdoor-traditional-sports-equipment",
        "nameEn": "Traditional Sports Equipment",
        "nameUr": "Traditional Sports Equipment"
      },
      {
        "slug": "sports-outdoor-sportswear-shoes",
        "nameEn": "Sportswear & Shoes",
        "nameUr": "Sportswear & Shoes"
      },
      {
        "slug": "sports-outdoor-swimming-water-sports",
        "nameEn": "Swimming & Water Sports",
        "nameUr": "Swimming & Water Sports"
      },
      {
        "slug": "sports-outdoor-other",
        "nameEn": "Other Sports Items",
        "nameUr": "Other Sports Items"
      }
    ]
  },
  {
    "slug": "baby-kids",
    "nameEn": "Baby & Kids",
    "nameUr": "بچوں کا سامان",
    "icon": "stroller",
    "sort": 23,
    "subcategories": [
      {
        "slug": "baby-kids-prams-strollers",
        "nameEn": "Prams & Strollers",
        "nameUr": "Prams & Strollers"
      },
      {
        "slug": "baby-kids-baby-cots-cribs",
        "nameEn": "Baby Cots & Cribs",
        "nameUr": "Baby Cots & Cribs"
      },
      {
        "slug": "baby-kids-car-seats",
        "nameEn": "Car Seats",
        "nameUr": "Car Seats"
      },
      {
        "slug": "baby-kids-baby-clothing",
        "nameEn": "Baby Clothing",
        "nameUr": "Baby Clothing"
      },
      {
        "slug": "baby-kids-toys-games",
        "nameEn": "Toys & Games",
        "nameUr": "Toys & Games"
      },
      {
        "slug": "baby-kids-kids-furniture",
        "nameEn": "Kids' Furniture",
        "nameUr": "Kids' Furniture"
      },
      {
        "slug": "baby-kids-baby-feeding-bottles",
        "nameEn": "Baby Feeding & Bottles",
        "nameUr": "Baby Feeding & Bottles"
      },
      {
        "slug": "baby-kids-diapers-baby-care",
        "nameEn": "Diapers & Baby Care",
        "nameUr": "Diapers & Baby Care"
      },
      {
        "slug": "baby-kids-kids-bicycles-ride-ons",
        "nameEn": "Kids' Bicycles & Ride-Ons",
        "nameUr": "Kids' Bicycles & Ride-Ons"
      },
      {
        "slug": "baby-kids-kids-books",
        "nameEn": "Kids' Books",
        "nameUr": "Kids' Books"
      },
      {
        "slug": "baby-kids-other",
        "nameEn": "Other Baby Items",
        "nameUr": "Other Baby Items"
      }
    ]
  },
  {
    "slug": "books-hobbies-collectibles",
    "nameEn": "Books, Hobbies & Collectibles",
    "nameUr": "کتب اور مشاغل",
    "icon": "menu_book",
    "sort": 24,
    "subcategories": [
      {
        "slug": "books-hobbies-collectibles-books",
        "nameEn": "Books (General)",
        "nameUr": "Books (General)"
      },
      {
        "slug": "books-hobbies-collectibles-religious-items",
        "nameEn": "Religious Items (Quran, Tasbeeh, Janamaz)",
        "nameUr": "Religious Items (Quran, Tasbeeh, Janamaz)"
      },
      {
        "slug": "books-hobbies-collectibles-musical-instruments",
        "nameEn": "Musical Instruments",
        "nameUr": "Musical Instruments"
      },
      {
        "slug": "books-hobbies-collectibles-art-craft-supplies",
        "nameEn": "Art & Craft Supplies",
        "nameUr": "Art & Craft Supplies"
      },
      {
        "slug": "books-hobbies-collectibles-coins-stamps-currency",
        "nameEn": "Coins, Stamps & Currency",
        "nameUr": "Coins, Stamps & Currency"
      },
      {
        "slug": "books-hobbies-collectibles-antiques",
        "nameEn": "Antiques",
        "nameUr": "Antiques"
      },
      {
        "slug": "books-hobbies-collectibles-collectibles-memorabilia",
        "nameEn": "Collectibles & Memorabilia",
        "nameUr": "Collectibles & Memorabilia"
      },
      {
        "slug": "books-hobbies-collectibles-board-games-puzzles",
        "nameEn": "Board Games & Puzzles",
        "nameUr": "Board Games & Puzzles"
      },
      {
        "slug": "books-hobbies-collectibles-photography-equipment",
        "nameEn": "Photography Equipment",
        "nameUr": "Photography Equipment"
      },
      {
        "slug": "books-hobbies-collectibles-drones-gadgets",
        "nameEn": "Drones & Gadgets",
        "nameUr": "Drones & Gadgets"
      },
      {
        "slug": "books-hobbies-collectibles-other",
        "nameEn": "Other Hobby Items",
        "nameUr": "Other Hobby Items"
      }
    ]
  },
  {
    "slug": "garden-plants-nursery",
    "nameEn": "Garden, Plants & Nursery",
    "nameUr": "باغبانی اور نرسری",
    "icon": "yard",
    "sort": 25,
    "subcategories": [
      {
        "slug": "garden-plants-nursery-fruit-saplings",
        "nameEn": "Fruit Saplings",
        "nameUr": "Fruit Saplings"
      },
      {
        "slug": "garden-plants-nursery-ornamental-plants",
        "nameEn": "Ornamental Plants",
        "nameUr": "Ornamental Plants"
      },
      {
        "slug": "garden-plants-nursery-flower-plants-seeds",
        "nameEn": "Flower Plants & Seeds",
        "nameUr": "Flower Plants & Seeds"
      },
      {
        "slug": "garden-plants-nursery-vegetable-seedlings",
        "nameEn": "Vegetable Seedlings",
        "nameUr": "Vegetable Seedlings"
      },
      {
        "slug": "garden-plants-nursery-indoor-plants",
        "nameEn": "Indoor Plants",
        "nameUr": "Indoor Plants"
      },
      {
        "slug": "garden-plants-nursery-flower-pots-planters",
        "nameEn": "Flower Pots & Planters",
        "nameUr": "Flower Pots & Planters"
      },
      {
        "slug": "garden-plants-nursery-garden-tools",
        "nameEn": "Garden Tools",
        "nameUr": "Garden Tools"
      },
      {
        "slug": "garden-plants-nursery-garden-soil-compost",
        "nameEn": "Garden Soil & Compost",
        "nameUr": "Garden Soil & Compost"
      },
      {
        "slug": "garden-plants-nursery-lawn-grass",
        "nameEn": "Lawn & Grass",
        "nameUr": "Lawn & Grass"
      },
      {
        "slug": "garden-plants-nursery-nursery-stock",
        "nameEn": "Nursery Stock (Bulk)",
        "nameUr": "Nursery Stock (Bulk)"
      },
      {
        "slug": "garden-plants-nursery-other",
        "nameEn": "Other Garden Items",
        "nameUr": "Other Garden Items"
      }
    ]
  },
  {
    "slug": "community",
    "nameEn": "Community",
    "nameUr": "کمیونٹی",
    "icon": "groups",
    "sort": 26,
    "subcategories": [
      {
        "slug": "community-free-giveaway",
        "nameEn": "Free & Giveaway",
        "nameUr": "Free & Giveaway"
      },
      {
        "slug": "community-lost-found",
        "nameEn": "Lost & Found",
        "nameUr": "Lost & Found"
      },
      {
        "slug": "community-charity-welfare-appeals",
        "nameEn": "Charity & Welfare Appeals",
        "nameUr": "Charity & Welfare Appeals"
      },
      {
        "slug": "community-local-announcements",
        "nameEn": "Local Announcements",
        "nameUr": "Local Announcements"
      },
      {
        "slug": "community-volunteer-social-work",
        "nameEn": "Volunteer & Social Work",
        "nameUr": "Volunteer & Social Work"
      },
      {
        "slug": "community-carpool-ride-share",
        "nameEn": "Carpool & Ride Share",
        "nameUr": "Carpool & Ride Share"
      },
      {
        "slug": "community-other",
        "nameEn": "Other Community Posts",
        "nameUr": "Other Community Posts"
      }
    ]
  }
];

export const CATEGORY_OPTIONS: SelectOption[] = CATEGORIES.map((c) => ({
  value: c.slug,
  label: c.nameEn,
  icon: c.icon,
}));

export function allSubcategoryOptions(): SelectOption[] {
  return CATEGORIES.flatMap((c) =>
    c.subcategories.map((s) => ({
      value: s.slug,
      label: `${c.nameEn} › ${s.nameEn}`,
      icon: c.icon,
    }))
  );
}

export function findCategory(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}
